'use strict';

const cron = require('node-cron');
const nodemailer = require('nodemailer');
const { generateDashboardPdf } = require('./pdfGenerator');

/**
 * Reads schedule config from environment variables and sets up a cron job
 * that generates the PDF dashboard and emails it to the configured recipients.
 */
function startScheduler() {
  const {
    SMTP_HOST,
    SMTP_PORT,
    SMTP_SECURE,
    SMTP_USER,
    SMTP_PASS,
    SMTP_FROM,
    REPORT_EMAILS,
    REPORT_SCHEDULE_DAY,
    REPORT_SCHEDULE_TIME,
  } = process.env;

  // If no SMTP host is configured, skip scheduling silently
  if (!SMTP_HOST || !REPORT_EMAILS) {
    console.log('[Scheduler] SMTP_HOST or REPORT_EMAILS not configured — email reporting disabled.');
    return;
  }

  const day = parseInt(REPORT_SCHEDULE_DAY, 10) || 1;
  const [hour, minute] = (REPORT_SCHEDULE_TIME || '08:00').split(':').map(Number);
  const cronExpression = `${minute ?? 0} ${hour ?? 8} ${day} * *`;

  console.log(`[Scheduler] Monthly report scheduled: day=${day}, time=${REPORT_SCHEDULE_TIME ?? '08:00'} (cron: "${cronExpression}")`);

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT, 10) || 587,
    secure: SMTP_SECURE === 'true',
    auth: SMTP_USER && SMTP_PASS ? { user: SMTP_USER, pass: SMTP_PASS } : undefined,
  });

  const recipients = REPORT_EMAILS.split(',').map((e) => e.trim()).filter(Boolean);

  // The frontend URL accessible from within the Docker network
  const frontendUrl = `http://frontend:80`;

  cron.schedule(cronExpression, async () => {
    const now = new Date();
    console.log(`[Scheduler] Generating monthly report at ${now.toISOString()}…`);

    try {
      const pdfBuffer = await generateDashboardPdf(frontendUrl);

      const monthLabel = now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
      const filename = `WheresMyMoney_Report_${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}.pdf`;

      await transporter.sendMail({
        from: SMTP_FROM || '"WheresMyMoney!" <reports@wheresmymoney.local>',
        to: recipients.join(', '),
        subject: `📊 WheresMyMoney! Monthly Report — ${monthLabel}`,
        html: `
          <h2>📊 WheresMyMoney! Monthly Report</h2>
          <p>Hi,</p>
          <p>Please find attached your financial dashboard report for <strong>${monthLabel}</strong>.</p>
          <p>This report was automatically generated by <em>WheresMyMoney!</em>.</p>
          <br/>
          <p style="color: #666; font-size: 0.85em;">
            You are receiving this because your email address is listed in REPORT_EMAILS.<br/>
            To unsubscribe, remove your address from the REPORT_EMAILS environment variable.
          </p>
        `,
        attachments: [
          {
            filename,
            content: pdfBuffer,
            contentType: 'application/pdf',
          },
        ],
      });

      console.log(`[Scheduler] Report sent successfully to: ${recipients.join(', ')}`);
    } catch (err) {
      console.error('[Scheduler] Failed to generate or send report:', err);
    }
  });
}

module.exports = { startScheduler };
